### PR TITLE
1061146 bug

### PR DESCRIPTION
**Pull request by xiang5337**
## Ready State
**Ready**

## Summary
- test
## Ticket
[1061146](https://portal.yopeso.com/task/1061146) 

## Testing
- no test

### CODE REVIEW

**Comment by ebarnad** [comment]
## Files associated with bugs
There's no suspicious file found

## Files associated with tickets
<table><tr><th>Filename</th><th>Tickets</th></tr><tr><td>lumen-framework/bootstrap/app.php</td><td><a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr><tr><td>lumen-framework/public/index.php</td><td><a href='https://portal.yopeso.com/task/1059621'>1059621</a>,<a href='https://portal.yopeso.com/task/1059568'>1059568</a>,<a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr><tr><td>lumen-framework/routes/web.php</td><td><a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr></table>

**Comment by ian9012** [comment]
## Files associated with bugs
<table><tr><th>Filename</th><th>Bug Tickets</th></tr><tr><td>lumen-framework/bootstrap/app.php</td><td><a href='https://portal.yopeso.com/task/1061168'>1061168</a></td></tr><tr><td>lumen-framework/public/index.php</td><td><a href='https://portal.yopeso.com/task/1060097'>1060097</a></td></tr></table>

## Files associated with tickets
<table><tr><th>Filename</th><th>Tickets</th></tr><tr><td>lumen-framework/bootstrap/app.php</td><td><a href='https://portal.yopeso.com/task/1061168'>1061168</a>,<a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr><tr><td>lumen-framework/public/index.php</td><td><a href='https://portal.yopeso.com/task/1060097'>1060097</a>,<a href='https://portal.yopeso.com/task/1059621'>1059621</a>,<a href='https://portal.yopeso.com/task/1059568'>1059568</a>,<a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr><tr><td>lumen-framework/routes/web.php</td><td><a href='https://portal.yopeso.com/task/1059491'>1059491</a></td></tr></table>

**Comment by ebarnad** [comment]
## Suspected Commits
There's no suspected commits found

**Comment by ebarnad** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>lumen-framework/composer.json</td></tr></table>

**Comment by ebarnad** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>lumen-framework/composer.json</td></tr></table>

**Comment by ian9012** [comment]
## Suspected Commits
There's no suspected commits found

**Comment by ebarnad** [comment]
## Suspected Commits
There's no suspected commits found

**Pull request closed without merging**
