### PR TITLE
Update method name - ignore file prerequisite 2 for case2

### PR DESCRIPTION
**Pull request by ebarnad**
## Ready State
**Ready**

## Summary
- After bug ticket reported
## Ticket
[1060963](https://portal.yopeso.com/task/1060963) 

## Testing
- no test

### CODE REVIEW

**Comment by ian9012** [comment]
## Files associated with bugs
There's no suspicious file found

## Files associated with tickets
There is no previous tickets found

**Comment by ebarnad** [comment]
Tets

**Comment by ebarnad** [comment]
## Suspected Commits
<table><tr><th>Commits</th></tr><tr><td><a href='https://github.com/xiangtest/pythia-test-live/commit/ceff688f28da2d868efb1e26d04620d7960315eb'>ceff688f28da2d868efb1e26d04620d7960315eb</a></td></tr></table>

**Comment by ebarnad** [comment]
## Files associated with bugs
<table><tr><th>Filename</th><th>Bug Tickets</th></tr><tr><td>lumen-framework/ignorefiles/IgnoreFileCase2.php</td><td><a href='https://portal.yopeso.com/task/1060959'>1060959</a></td></tr></table>

## Files associated with tickets
<table><tr><th>Filename</th><th>Tickets</th></tr><tr><td>lumen-framework/ignorefiles/IgnoreFileCase2.php</td><td><a href='https://portal.yopeso.com/task/1060959'>1060959</a></td></tr></table>

**Comment by ebarnad** [comment]
## Files associated with bugs
<table><tr><th>Filename</th><th>Bug Tickets</th></tr><tr><td>lumen-framework/ignorefiles/IgnoreFileCase2.php</td><td><a href='https://portal.yopeso.com/task/1060963'>1060963</a>,<a href='https://portal.yopeso.com/task/1060959'>1060959</a></td></tr></table>

## Files associated with tickets
<table><tr><th>Filename</th><th>Tickets</th></tr><tr><td>lumen-framework/ignorefiles/IgnoreFileCase2.php</td><td><a href='https://portal.yopeso.com/task/1060963'>1060963</a>,<a href='https://portal.yopeso.com/task/1060959'>1060959</a></td></tr></table>

**Comment by ebarnad** [comment]
## Suspected Commits
<table><tr><th>Commits</th></tr><tr><td><a href='https://github.com/xiangtest/pythia-test-live/commit/ceff688f28da2d868efb1e26d04620d7960315eb'>ceff688f28da2d868efb1e26d04620d7960315eb</a></td></tr></table>

**Pull request merged**
