### PR TITLE
1061136 Bug test bug cache refresh 1

### PR DESCRIPTION
**Pull request by xiang5337**
## Ready State
**Ready**

## Summary
- Bug test bug cache refresh 1
## Ticket
[1061136](https://portal.yopeso.com/task/1061136) 

## Testing
- no test

### CODE REVIEW

**Comment by xiang5337** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>lumen-framework/composer.json</td></tr></table>

**Comment by ian9012** [comment]
## Files associated with bugs
<table><tr><th>Filename</th><th>Bug Tickets</th></tr><tr><td>README.md</td><td><a href='https://portal.yopeso.com/task/1060920'>1060920</a>,<a href='https://portal.yopeso.com/task/1061082'>1061082</a>,<a href='https://portal.yopeso.com/task/1060920'>1060920</a></td></tr></table>

## Files associated with tickets
<table><tr><th>Filename</th><th>Tickets</th></tr><tr><td>README.md</td><td><a href='https://portal.yopeso.com/task/1061135'>1061135</a>,<a href='https://portal.yopeso.com/task/1060920'>1060920</a>,<a href='https://portal.yopeso.com/task/1061082'>1061082</a>,<a href='https://portal.yopeso.com/task/1060920'>1060920</a>,<a href='https://portal.yopeso.com/task/1059538'>1059538</a>,<a href='https://portal.yopeso.com/task/1059538'>1059538</a>,<a href='https://portal.yopeso.com/task/1059491'>1059491</a>,<a href='https://portal.yopeso.com/task/1059493'>1059493</a></td></tr></table>

**Comment by ian9012** [comment]
## Suspected Commits
<table><tr><th>Commits</th></tr><tr><td><a href='https://github.com/xiangtest/pythia-test-live/commit/05a663a4780e39a0ec7eca9d3cd7a7071cb1b9a0'>05a663a4780e39a0ec7eca9d3cd7a7071cb1b9a0</a></td></tr></table>

**Comment by ian9012** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>lumen-framework/composer.json</td></tr></table>

**Comment by ian9012** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>README.md</td></tr></table>

**Comment by xiang5337** [comment]
## Files associated with bug cache
<table><tr><th>Prioritized file</th></tr><tr><td>lumen-framework/bootstrap/app.php</td></tr><tr><td>lumen-framework/app/Exceptions/Handler.php</td></tr><tr><td>lumen-framework/app/Http/Middleware/Authenticate.php</td></tr><tr><td>README.md</td></tr></table>

**Comment by ebarnad** [comment]
## Suspected Commits
There's no suspected commits found

**Pull request merged**
